require 'spec_helper'

RSpec.describe AttachmentToHTML::Adapters::RTF do
  let(:attachment) do
    FoiAttachment.new(
      content_type: 'application/rtf',
      filename: 'interesting.rtf',
      body: load_file_fixture('interesting.rtf')
    )
  end
  let(:adapter) { AttachmentToHTML::Adapters::RTF.new(attachment) }

  describe :tmpdir do
    it 'defaults to the rails tmp directory' do
      expect(adapter.tmpdir).to eq(Rails.root.join('tmp'))
    end

    it 'allows a tmpdir to be specified to store the converted document' do
      adapter = AttachmentToHTML::Adapters::RTF.new(attachment, tmpdir: '/tmp')
      expect(adapter.tmpdir).to eq('/tmp')
    end
  end

  describe :title do
    it 'uses the attachment filename for the title' do
      expect(adapter.title).to eq(attachment.display_filename)
    end
  end

  describe :body do
    it 'extracts the body from the document' do
      expect(adapter.body).to include('thisisthebody')
    end

    it 'operates in the context of the supplied tmpdir' do
      adapter = AttachmentToHTML::Adapters::RTF.new(attachment, tmpdir: '/tmp')
      expect(Dir).to receive(:chdir).with('/tmp').and_call_original
      adapter.body
    end

    it 'does not result in incorrect conversion when unrtf returns an invalid doctype' do
      # Doctype public identifier is unquoted
      # Valid doctype would be:
      # <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
      # See bug report http://savannah.gnu.org/bugs/?42015
      invalid = <<-DOC
      <!DOCTYPE html PUBLIC -//W3C//DTD HTML 4.01 Transitional//EN>
      <html>
      <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8">
      <!-- Translation from RTF performed by UnRTF, version 0.21.5 -->
      <!--font table contains 0 fonts total-->
      <!--invalid font number 0-->
      </head>
      <body><font size="3"><font color="#000000">thisisthebody</font></font></body>
      </html>
      DOC
      allow(AlaveteliExternalCommand).to receive(:run).and_return(invalid)

      expect(adapter.body).not_to include('//W3C//DTD HTML 4.01 Transitional//EN')
    end

    it 'converts empty files' do
      attachment = FoiAttachment.new(
        content_type: 'application/rtf',
        body: load_file_fixture('empty.rtf')
      )
      adapter = AttachmentToHTML::Adapters::RTF.new(attachment)
      expect(adapter.body).to eq('')
    end

    it 'doesnt fail if the external command returns nil' do
      allow(AlaveteliExternalCommand).to receive(:run).and_return(nil)
      expect(adapter.body).to eq('')
    end

    it 'sanitizes malicious files' do
      attachment = FoiAttachment.new(
        content_type: 'application/rtf',
        body: load_file_fixture('rtf-xss.rtf')
      )
      adapter = AttachmentToHTML::Adapters::RTF.new(attachment)
      expect(adapter.body).not_to include('<script>alert(1)</script>')
    end

    context 'when the document injects a form' do
      let(:attachment) do
        FoiAttachment.new(
          content_type: 'application/rtf',
          body: load_file_fixture('rtf-form.rtf')
        )
      end

      it 'removes the form and its controls' do
        expect(adapter.body).not_to match(/<(form|input|button)/)
        expect(adapter.body).not_to include('evil.example')
      end

      it 'keeps the injected content as inert text' do
        expect(adapter.body).to include(
          '<p>Session expired. Please log in again.</p>Log in'
        )
      end

      it 'keeps the document text' do
        expect(adapter.body).to include('Please find attached our response.')
        expect(adapter.body).to include('Kind regards')
      end
    end

    it 'keeps markup generated by unrtf' do
      html = <<~HTML
        <body><b>Bold</b><center><big>Big</big><small>Small</small></center>
        <table border="1"><tr><td align="left">Cell</td></tr></table>
        <a href="https://example.com/">Link</a><img src="image.png"></body>
      HTML
      allow(AlaveteliExternalCommand).to receive(:run).and_return(html)

      expect(adapter.body).to include(
        '<b>Bold</b>',
        '<center>',
        '<big>Big</big><small>Small</small>',
        '<td align="left">Cell</td>',
        '<a href="https://example.com/">Link</a>',
        '<img src="image.png">'
      )
    end

    it 'removes font and style formatting, keeping the content' do
      html = '<body><font face="Arial" size="3" color="#000000">' \
             '<span style="font-size:11pt">Text</span></font></body>'
      allow(AlaveteliExternalCommand).to receive(:run).and_return(html)

      expect(adapter.body).to eq('<span>Text</span>')
    end

    describe 'interactive and active content' do
      let(:attachment) do
        FoiAttachment.new(
          content_type: 'application/rtf',
          body: load_file_fixture('rtf-interactive.rtf')
        )
      end

      let(:scrubbed) { Nokogiri::HTML5.fragment(adapter.body) }

      %w(
        form input button textarea select optgroup option datalist output
        fieldset legend label iframe frame object embed base link meta script
        style svg dialog details summary
      ).each do |element|
        it "removes #{element} elements" do
          expect(scrubbed.css(element)).to be_empty
        end
      end

      %w(
        action method formaction onclick onmouseover target id name type for
        open
      ).each do |attribute|
        it "removes #{attribute} attributes" do
          expect(scrubbed.xpath("//@#{attribute}")).to be_empty
        end
      end
    end

    it 'unwraps unexpected elements, keeping their content' do
      html = '<body><blockquote class="x"><p>Quoted</p></blockquote></body>'
      allow(AlaveteliExternalCommand).to receive(:run).and_return(html)

      expect(adapter.body).to eq('<p>Quoted</p>')
    end

    it 'removes non-text elements along with their content' do
      html = '<body><p>Text</p><script>alert(1)</script>' \
             '<style>p { display: none }</style>' \
             '<iframe src="https://example.com/">Framed</iframe>' \
             '<svg><text>Vector</text></svg><math><mi>x</mi></math></body>'
      allow(AlaveteliExternalCommand).to receive(:run).and_return(html)

      expect(adapter.body).to eq('<p>Text</p>')
    end

    it 'removes unsafe link protocols' do
      html = '<body><a href="javascript:alert(1)">Link</a></body>'
      allow(AlaveteliExternalCommand).to receive(:run).and_return(html)

      expect(adapter.body).to eq('<a>Link</a>')
    end
  end

  describe :success? do
    it 'is truthy if the body has content excluding the tags' do
      allow(adapter).to receive(:body).and_return('<p>some content</p>')
      expect(adapter.success?).to be_truthy
    end

    it 'is truthy if the body contains images' do
      allow(adapter).to receive(:body).and_return(%Q(<img src="logo.png" />))
      expect(adapter.success?).to be_truthy
    end

    it 'is falsey if the body has no content other than tags' do
      allow(adapter).to receive(:body).and_return('<p></p>')
      expect(adapter.success?).to be_falsey
    end
  end
end
