#!/bin/sh

cd "$(dirname "$0")/.."

. docker/env

docker compose down

DB_VOLUME="$(basename $(pwd))_postgres"
if docker volume ls | grep $DB_VOLUME >/dev/null; then
  while true
  do
    read -r -p 'Do you also want to reset your development database? ' choice
    case "$choice" in
      n|N) break;;
      y|Y)
        docker volume rm $DB_VOLUME >/dev/null
        data_reset=true
        break;;
      *) echo 'Response not valid';;
    esac
  done
fi

docker compose build --pull

./docker/setup $data_reset
