#!/bin/sh

set -e

cd "$(dirname "$0")/.."

source docker/env

docker compose down

db_volume="$(basename $(pwd))_postgres"
if docker volume ls | grep $db_volume >/dev/null; then
  while true
  do
    read -r -p 'Do you also want to reset your development database? ' choice
    case "$choice" in
      n|N) break;;
      y|Y)
        docker volume rm $db_volume >/dev/null
        data_reset=true
        break;;
      *) echo 'Response not valid';;
    esac
  done
fi

docker compose build --pull

./docker/setup $data_reset
