require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # CUSTOM CONFIGURATION
  #
  # Always place custom environment config at the bottom of the file
  # to make Rails upgrades easier.
  # ----------------------------------------------------------------

  config.action_mailer.preview_paths = [
    Rails.root.join('spec', 'mailers', 'previews')
  ]

  # Set RAILS_LOG_LEVEL in the environment to a valid log level to temporarily
  # run the application with a non-default setting.
  config.log_level = ENV.fetch('RAILS_LOG_LEVEL', :debug)

  # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
  # the I18n.default_locale when a translation cannot be found).
  config.i18n.fallbacks = true

  if AlaveteliConfiguration.use_mailcatcher_in_development
    # So is queued, rather than giving immediate errors
    config.action_mailer.delivery_method = :smtp
    smtp = URI.parse(ENV.fetch('SMTP_URL', 'smtp://localhost:1025'))
    config.action_mailer.smtp_settings = { address: smtp.host, port: smtp.port }
  else
    config.action_mailer.delivery_method = :sendmail
  end

  # Allow any IP address in the range 10.10.10.x to access the web console
  config.web_console.allowed_ips = '10.10.10.0/16'

  # Writes useful log files to debug memory leaks, of the sort where have
  # unintentionally kept references to objects, especially strings.
  # require 'memory_profiler'
  # MemoryProfiler.start :string_debug => true, :delay => 10

  if AlaveteliConfiguration.use_bullet_in_development
    config.after_initialize do
      Bullet.enable = true
      Bullet.bullet_logger = true
      Bullet.console = true
      Bullet.add_footer = true
    end
  end
end
