# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "users", :force => true do |t|
    t.column "email",           :string
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
