#!/bin/bash

# Clear the cache of attachment and body text.

LOC=`dirname $0`

$LOC/runner "ActiveRecord::Base.connection.execute(\"update incoming_messages set cached_attachment_text_clipped = null, cached_main_body_text = null\")"

# Remove page cache (do it in two stages so live site gets cache cleared faster)
rm -fr $LOC/../old-cache
mv $LOC/../cache $LOC/../old-cache
rm -fr $LOC/../old-cache

