#!/bin/bash

RAILS_ENV=$1
set -e
if [ -x /usr/bin/xapian-compact ]; then
    XAPIAN_DB_DIR="$( cd "$( dirname "$0" )" && pwd )/../vendor/plugins/acts_as_xapian/xapiandbs"
    OWNER=`stat -c %U $XAPIAN_DB_DIR/$RAILS_ENV`
    su -c "xapian-compact $XAPIAN_DB_DIR/$RAILS_ENV $XAPIAN_DB_DIR/$RAILS_ENV.new" $OWNER
    mv $XAPIAN_DB_DIR/$RAILS_ENV $XAPIAN_DB_DIR/$RAILS_ENV.tmp
    mv $XAPIAN_DB_DIR/$RAILS_ENV.new $XAPIAN_DB_DIR/$RAILS_ENV
    rm -rf $XAPIAN_DB_DIR/$RAILS_ENV.tmp
    /etc/init.d/apache2 restart
else
    echo "Could not find xapian-compact script; have you installed xapian-tools?"
    exit 1
fi