#!/bin/bash

# Fill in all the database caches of text from body/attachments.
# Will take a while to run! Can use after clear-caches to refresh the database
# level caches if you like.

LOC=`dirname $0`

"$LOC/runner" 'IncomingMessage.find_each() { |im| print im.id.to_s + " id: main body folded:" + im.get_main_body_text_folded.size.to_s + " attachment clipped:" + im.get_attachment_text_clipped.size.to_s + "\n" }'


