#!/bin/bash

# This script loads spec fixtures, but also needs to do a hack around
# the fact that the fixtures aren't aware of the fact that RawEmails
# have a filesystem representation of their contents

export LOC=`dirname "$0"`

bundle exec rails runner /dev/stdin <<END
require "spec/spec_helper.rb"

# HACK: Normally to load fixtures you'd run `rake db:fixtures:load` but since we
# have .csv files in the fixtures folder Rails tries to load those too. Therefore
# we've pinched some code to load the fixtures:
# https://github.com/rails/rails/blob/5ecd14c5f16533d09c01007bf5d70f70a59c30e3/activerecord/lib/active_record/railties/databases.rake#L319
fixtures_dir = "#{ENV['LOC']}/../spec/fixtures"

Dir["#{fixtures_dir}/**/*.yml"].each do |fixture_file|
  Fixtures.create_fixtures(fixtures_dir, fixture_file[(fixtures_dir.size + 1)..-5])
end

load_raw_emails_data
END

echo "Loaded fixtures.  You may now wish to run $LOC/update-xapian-index"
