#!/bin/bash

LOC=`dirname "$0"`

# Specific file if specified
if [ x$1 != x ]
then
    case "$1" in
      /*) f=$1 ;;
       *) f=$(pwd)/$1 ;;
    esac
    cd "$LOC"
    bundle exec ./runner 'EximLog.load_file("'$f'")'
    exit
fi

# Load in last three days worth of logs (if they've been modified)
cd "$LOC"
LATEST=$( ls /var/log/exim4/exim-mainlog-* 2>/dev/null | sort | tail -3 )
for X in $LATEST
do
    bundle exec ./runner 'EximLog.load_file("'$X'")'
done
