#!/bin/bash

TOP_DIR="$(dirname "$BASH_SOURCE")/.."
cd "$TOP_DIR"

if [ "$1" == "--loop" ]
then
  bundle exec rails runner 'PurgeRequest.purge_all_loop'
else
  bundle exec rails runner 'PurgeRequest.purge_all'
fi

