#!/bin/bash
#
# rails-post-deploy
# For Ruby on Rails, this used to be run in exec_extras in vhosts.pl;
# however, now we use exec_before_down and exec_while_down instead, so
# this is here for compatability with alternative deploy scripts that
# still call rails-post-deploy.
#
# Copyright (c) 2007 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org; WWW: http://www.mysociety.org/

set -e
#set -x # debug

APP_ROOT="$(dirname "$BASH_SOURCE")/.."
cd "$APP_ROOT"

"$APP_ROOT/script/rails-deploy-before-down"
"$APP_ROOT/script/rails-deploy-while-down"
