#!/bin/bash
# request-creation-graph
# Plot graph of rate of request creation
#
# Copyright (c) 2008 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org. WWW: http://www.mysociety.org/

cd `dirname $0`
bundle exec rake "$@" graphs:generate_request_creation_graph

