#!/bin/bash
# request-creation-graph
# Plot graph of rate of request creation
#
# Copyright (c) 2008 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org. WWW: http://www.mysociety.org/
# 
# $Id: request-creation-graph,v 1.6 2008-05-09 01:34:24 francis Exp $

GPLOT_OUTPUT="set terminal png font 'Vera.ttf' 9 size 1200,400"
EXTENSION=".png"
#GPLOT_OUTPUT="set terminal fig color big thickness 1"
#EXTENSION=".fig"
#GPLOT_OUTPUT="set terminal svg size 800 250"
#EXTENSION=".svg"

cd `dirname $0`
cd ../../
source shlib/deployfns

# XXX this is nasty :)
OPTION_FOI_DB_HOST=`grep "host:" foi/config/database.yml | head --lines=1 | cut -d ":" -f 2`
OPTION_FOI_DB_PORT=`grep "port:" foi/config/database.yml | head --lines=1 | cut -d ":" -f 2`
OPTION_FOI_DB_NAME=`grep "database:" foi/config/database.yml | head --lines=1 | cut -d ":" -f 2`
OPTION_FOI_DB_USER=`grep "username:" foi/config/database.yml | head --lines=1 | cut -d ":" -f 2`

SOURCEA=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCEB=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCEC=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCED=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCEE=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCEF=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
SOURCEG=/tmp/foi-creation-rate-graph-data-$RANDOM$RANDOM
GPSCRIPT=/tmp/foi-creation-rate-graph-script-$RANDOM$RANDOM

#    where status in ('draft') 

function grab_data {
    echo "select 
        date(created_at), count(*)
        from info_requests
        $1
        and prominence != 'backpage'
        group by date(created_at)
        order by date(created_at)
        ;" | psql --host $OPTION_FOI_DB_HOST --port $OPTION_FOI_DB_PORT -A -F " " $OPTION_FOI_DB_NAME $OPTION_FOI_DB_USER | egrep -v "date|rows" >$2
}

# rather nastily, work out the cumulative heights in reverse, so can plot impulses on top of each other
grab_data "where (1 = 1)" $SOURCEA
grab_data "where described_state not in ('waiting_response')" $SOURCEB
grab_data "where described_state not in ('waiting_response', 'waiting_clarification')" $SOURCEC
grab_data "where described_state not in ('waiting_response', 'waiting_clarification', 'not_held')" $SOURCED
grab_data "where described_state not in ('waiting_response', 'waiting_clarification', 'not_held', 'rejected')" $SOURCEE
grab_data "where described_state not in ('waiting_response', 'waiting_clarification', 'not_held', 'rejected', 'successful')" $SOURCEF
grab_data "where described_state not in ('waiting_response', 'waiting_clarification', 'not_held', 'rejected', 'successful', 'partially_successful')" $SOURCEG


#state = 'unconfirmed'
#or state = 'confirmed'
#or state = 'fixed'
#or state = 'hidden'
#or state = 'flickr'


cat >$GPSCRIPT <<END 
    unset border
    unset arrow
    set key left
    set tics out
    $GPLOT_OUTPUT

    set xdata time
    set timefmt "%Y-%m-%d"
    set xrange ["2007-12-01":]
    set format x "%d %b %Y"
    set xtics nomirror
    set xlabel "status of requests that were created on each calendar day"

    set ytics nomirror 
    set ylabel "number of requests created on the calendar day" 
    set y2tics tc lt 2
    set y2label "cumulative total number of requests" tc lt 2
    set format y2 "%.0f"

#    set arrow 1 from '2005-02-14', 0 to '2005-02-14', 900 lt 0 nohead
#    set label 1 'launch of beta' at '2005-02-17', 900

    n = 0
    plot "$SOURCEA" using 1:2 with impulses lt 8 lw 15 title "waiting_response",\
         "$SOURCEB" using 1:2 with impulses lt 3 lw 15 title "waiting_clarification",\
         "$SOURCEC" using 1:2 with impulses lt 9 lw 15 title "not_held",\
         "$SOURCED" using 1:2 with impulses lt 6 lw 15 title "rejected",\
         "$SOURCEE" using 1:2 with impulses lt 2 lw 15 title "successful",\
         "$SOURCEF" using 1:2 with impulses lt 10 lw 15 title "partially_successful",\
         "$SOURCEG" using 1:2 with impulses lt 5 lw 15 title "requires_admin",\
    "< awk 'BEGIN { n = 0 } { n += \$2; print \$1, \$2, n; }' $SOURCEA" using 1:3 axes x1y2 with lines lt 2 title "cumulative total number of requests"
END
#echo "gpscript $GPSCRIPT"

export GDFONTPATH=/usr/share/fonts/truetype/ttf-bitstream-vera
gnuplot < $GPSCRIPT > foi/public/foi-live-creation$EXTENSION


