#!/bin/bash

# Stops and restarts the Mongrel web server.

cd `dirname $0`
cd ..
# XXX Include path for dodgy version of daemonize package
if [ -e log/mongrel.pid ]
then
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails stop
    sleep 5s
    if [ -e log/mongrel.pid ]
        if ( ps h -p `cat log/mongrel.pid` )
        then
            echo "kill -9 ing `cat log/mongrel.pid` because it failed to stop"
            kill -9 `cat log/mongrel.pid`
            sleep 2s
        fi
    fi
    if [ -e log/mongrel.pid ]
    then
        rm log/mongrel.pid
    fi
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails start -d --debug
else
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails start -d --debug
fi

