#!/bin/bash

# Stops and restarts the Mongrel web server.

cd `dirname $0`
cd ..
# XXX Include path for dodgy version of daemonize package
if [ -e log/mongrel.pid ]
then
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails stop
    sleep 1s
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails start -d
else
    ruby -I/usr/lib/ruby/ /usr/bin/mongrel_rails start -d
fi

