#!/usr/bin/ruby

daemon_mode = !ARGV.empty? && ARGV[0] == "--daemon"

script_dir = File.dirname(__FILE__)
alaveteli_dir = File.join(script_dir, "..")

Dir.chdir(alaveteli_dir) do
  require File.join(alaveteli_dir, 'config', 'boot')
  if daemon_mode
    # Run in daemon mode.
    #
    # If the environment variable PIDFILE is present,
    # write the pid of the daemon process to that file.
    
    pid = fork { require 'commands/runner' }
    if ENV.has_key? "PIDFILE"
      File.open(ENV["PIDFILE"], 'w') do |fh|
        fh.puts pid
      end
    end
    Process.detach(pid)
  else
    
    require 'commands/runner'
  end
end
