#!/bin/bash

# Try all ordered pairs of spec files,
# to winkle out order-dependent failures.

specs=spec/*/*.rb

for spec1 in $specs
do
    seen=false
    for spec2 in $specs
    do
        if [ "$spec1" != "$spec2" ]
        then
            rake db:test:purge
            rake db:test:clone_structure
            if ! ( script/spec "$spec1" "$spec2" ) > /dev/null
            then
                echo "FAILED: $spec1 $spec2"
            fi
        fi
    done
done
