class BigintForeignKeys < ActiveRecord::Migration[5.0]
  def up
    change_column :acts_as_xapian_jobs, :model_id, :bigint
    change_column :announcement_dismissals, :announcement_id, :bigint
    change_column :announcement_dismissals, :user_id, :bigint
    change_column :announcement_translations, :announcement_id, :bigint
    change_column :announcements, :user_id, :bigint
    change_column :censor_rules, :info_request_id, :bigint
    change_column :censor_rules, :public_body_id, :bigint
    change_column :censor_rules, :user_id, :bigint
    change_column :comments, :info_request_id, :bigint
    change_column :comments, :user_id, :bigint
    change_column :draft_info_request_batches, :user_id, :bigint
    change_column :draft_info_request_batches_public_bodies, :draft_info_request_batch_id, :bigint
    change_column :draft_info_request_batches_public_bodies, :public_body_id, :bigint
    change_column :draft_info_requests, :public_body_id, :bigint
    change_column :draft_info_requests, :user_id, :bigint
    change_column :embargo_extensions, :embargo_id, :bigint
    change_column :embargoes, :info_request_id, :bigint
    change_column :foi_attachments, :incoming_message_id, :bigint
    change_column :has_tag_string_tags, :model_id, :bigint
    change_column :info_request_batches, :user_id, :bigint
    change_column :info_request_batches_public_bodies, :info_request_batch_id, :bigint
    change_column :info_request_batches_public_bodies, :public_body_id, :bigint
    change_column :notifications, :info_request_event_id, :bigint
    change_column :notifications, :user_id, :bigint
    change_column :outgoing_messages, :incoming_message_followup_id, :bigint
    change_column :outgoing_messages, :info_request_id, :bigint
    change_column :post_redirects, :user_id, :bigint
    change_column :pro_accounts, :user_id, :bigint
    change_column :profile_photos, :user_id, :bigint
    change_column :public_body_category_links, :category_display_order, :bigint
    change_column :public_body_category_links, :public_body_category_id, :bigint
    change_column :public_body_category_links, :public_body_heading_id, :bigint
    change_column :public_body_category_translations, :public_body_category_id, :bigint
    change_column :public_body_change_requests, :public_body_id, :bigint
    change_column :public_body_change_requests, :user_id, :bigint
    change_column :public_body_heading_translations, :public_body_heading_id, :bigint
    change_column :public_body_translations, :public_body_id, :bigint
    change_column :public_body_versions, :public_body_id, :bigint
    change_column :request_classifications, :info_request_event_id, :bigint
    change_column :request_classifications, :user_id, :bigint
    change_column :request_summaries, :summarisable_id, :bigint
    change_column :request_summaries, :user_id, :bigint
    change_column :request_summaries_summary_categories, :request_summary_category_id, :bigint
    change_column :request_summaries_summary_categories, :request_summary_id, :bigint
    change_column :roles, :resource_id, :bigint
    change_column :track_things, :info_request_id, :bigint
    change_column :track_things, :public_body_id, :bigint
    change_column :track_things, :tracked_user_id, :bigint
    change_column :track_things, :tracking_user_id, :bigint
    change_column :track_things_sent_emails, :info_request_event_id, :bigint
    change_column :track_things_sent_emails, :public_body_id, :bigint
    change_column :track_things_sent_emails, :track_thing_id, :bigint
    change_column :track_things_sent_emails, :user_id, :bigint
    change_column :user_info_request_sent_alerts, :info_request_event_id, :bigint
    change_column :user_info_request_sent_alerts, :info_request_id, :bigint
    change_column :user_info_request_sent_alerts, :user_id, :bigint
    change_column :users_roles, :role_id, :bigint
    change_column :users_roles, :user_id, :bigint
    change_column :widget_votes, :info_request_id, :bigint
  end

  def down
    change_column :widget_votes, :info_request_id, :integer
    change_column :user_info_request_sent_alerts, :user_id, :integer
    change_column :user_info_request_sent_alerts, :info_request_id, :integer
    change_column :user_info_request_sent_alerts, :info_request_event_id, :integer
    change_column :users_roles, :user_id, :integer
    change_column :users_roles, :role_id, :integer
    change_column :track_things_sent_emails, :user_id, :integer
    change_column :track_things_sent_emails, :track_thing_id, :integer
    change_column :track_things_sent_emails, :public_body_id, :integer
    change_column :track_things_sent_emails, :info_request_event_id, :integer
    change_column :track_things, :tracking_user_id, :integer
    change_column :track_things, :tracked_user_id, :integer
    change_column :track_things, :public_body_id, :integer
    change_column :track_things, :info_request_id, :integer
    change_column :roles, :resource_id, :integer
    change_column :request_summaries_summary_categories, :request_summary_id, :integer
    change_column :request_summaries_summary_categories, :request_summary_category_id, :integer
    change_column :request_summaries, :user_id, :integer
    change_column :request_summaries, :summarisable_id, :integer
    change_column :request_classifications, :user_id, :integer
    change_column :request_classifications, :info_request_event_id, :integer
    change_column :public_body_versions, :public_body_id, :integer
    change_column :public_body_translations, :public_body_id, :integer
    change_column :public_body_heading_translations, :public_body_heading_id, :integer
    change_column :public_body_change_requests, :user_id, :integer
    change_column :public_body_change_requests, :public_body_id, :integer
    change_column :public_body_category_translations, :public_body_category_id, :integer
    change_column :public_body_category_links, :public_body_heading_id, :integer
    change_column :public_body_category_links, :public_body_category_id, :integer
    change_column :public_body_category_links, :category_display_order, :integer
    change_column :pro_accounts, :user_id, :integer
    change_column :profile_photos, :user_id, :integer
    change_column :post_redirects, :user_id, :integer
    change_column :outgoing_messages, :info_request_id, :integer
    change_column :outgoing_messages, :incoming_message_followup_id, :integer
    change_column :notifications, :user_id, :integer
    change_column :notifications, :info_request_event_id, :integer
    change_column :info_request_batches_public_bodies, :public_body_id, :integer
    change_column :info_request_batches_public_bodies, :info_request_batch_id, :integer
    change_column :info_request_batches, :user_id, :integer
    change_column :has_tag_string_tags, :model_id, :integer
    change_column :foi_attachments, :incoming_message_id, :integer
    change_column :embargo_extensions, :embargo_id, :integer
    change_column :embargoes, :info_request_id, :integer
    change_column :draft_info_request_batches_public_bodies, :public_body_id, :integer
    change_column :draft_info_request_batches_public_bodies, :draft_info_request_batch_id, :integer
    change_column :draft_info_request_batches, :user_id, :integer
    change_column :draft_info_requests, :user_id, :integer
    change_column :draft_info_requests, :public_body_id, :integer
    change_column :comments, :user_id, :integer
    change_column :comments, :info_request_id, :integer
    change_column :censor_rules, :user_id, :integer
    change_column :censor_rules, :public_body_id, :integer
    change_column :censor_rules, :info_request_id, :integer
    change_column :announcement_translations, :announcement_id, :integer
    change_column :announcement_dismissals, :user_id, :integer
    change_column :announcement_dismissals, :announcement_id, :integer
    change_column :announcements, :user_id, :integer
    change_column :acts_as_xapian_jobs, :model_id, :integer
  end
end
